name: Cowsay workflow
on:
  push:

jobs:
  cow:
    name: Cowsays
    runs-on: ubuntu-latest
    steps:
    - name: Cow Says now
      run: |
        echo "SOFT_FAIL=true" >> $GITHUB_ENV
    outputs:
      SOFT_FAIL: ${{ env.SOFT_FAIL }}

  cat:
    name: Cat says
    needs: [cow]
    if: needs.cow.outputs.SOFT_FAIL != 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Cat says now
      run: |
        echo ${{ needs.cow.outputs.SOFT_FAIL }}
        echo "Miao"

  dog:
    name: dog says
    needs: [cow]
    runs-on: ubuntu-latest
    steps:
    - name: dog says now
      run: |
        echo ${{ needs.cow.outputs.SOFT_FAIL }}
        echo "Bark"
