name: Cowsay workflow
on:
  push:

jobs:
  cow:
    name: Cowsays
    runs-on: ubuntu-latest
    steps:
    - name: Cow Says now
      run: |
        echo "SOFT_FAIL=false" >> $GITHUB_ENV

    - name: Cat says now
      if: env.SOFT_FAIL != true
      run: |
        echo ${{ env.SOFT_FAIL }}
        echo "Miao"

    - name: dog says now
      if: env.SOFT_FAIL == false
      run: |
        echo ${{ env.SOFT_FAIL }}
        echo "Bark"
