name: Cowsay workflow
on:
  push:

jobs:
  cow:
    name: Cowsays
    runs-on: ubuntu-latest
    steps:
    - name: Cow Says now
      run: |
        echo "SOFT_FAIL=true" >> $GITHUB_OUTPUT

  cat:
    name: Cat says
    needs: [cow]
    if: needs.cow.outputs.SOFT_FAIL != 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Cat says now
      run: |
        echo "Miao"
